---
version: "3.9"
services:

  database:
    image: mongo
    container_name: database
    environment:
      - MONGO_INITDB_DATABASE=database
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - test

  redis-json:
    image: redis/redis-stack:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=mypassword
    ports:
      - "6379:6379"
    networks:
      - test

volumes:
  mongo-data:

networks:
  test:
    name: test
    driver: bridge
